// Generated by CoffeeScript 1.8.0
(function() {
  var Organization;

  module.exports = Organization = (function() {
    function Organization() {
      this.resource = "organization";
      this.id = null;
      this.name = null;
      this.email = null;
      this.address = null;
      this.postalCode = null;
      this.city = null;
      this.country = null;
      this.countryCode = null;
      this.registrationType = null;
      this.registrationNumber = null;
      this.registrationDatetime = null;
      this.verifiedDatetime = null;
    }

    Organization.prototype.isValid = function() {
      return this.verifiedDatetime !== null;
    };

    return Organization;

  })();

}).call(this);
