// Generated by CoffeeScript 1.8.0
(function() {
  var Profile;

  module.exports = Profile = (function() {
    function Profile() {
      this.resource = "profile";
      this.id = null;
      this.mode = null;
      this.name = null;
      this.website = null;
      this.email = null;
      this.phone = null;
      this.categoryCode = null;
      this.status = null;
      this.review = null;
      this.createdDatetime = null;
      this.updatedDatetime = null;
      this.links = null;
    }

    Profile.prototype.isValid = function() {
      return this.status === "verified" && this.review === null;
    };

    return Profile;

  })();

}).call(this);
