// Generated by CoffeeScript 1.8.0
(function() {
  var Base, Organization, Organizations,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base");

  Organization = require("../object/organization");

  module.exports = Organizations = (function(_super) {
    __extends(Organizations, _super);

    function Organizations() {
      return Organizations.__super__.constructor.apply(this, arguments);
    }

    Organizations.resource = "organizations";

    Organizations.object = Organization;

    return Organizations;

  })(Base);

}).call(this);
