// Generated by CoffeeScript 1.8.0
(function() {
  var Base, Profile, Profiles,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base");

  Profile = require("../object/profile");

  module.exports = Profiles = (function(_super) {
    __extends(Profiles, _super);

    function Profiles() {
      return Profiles.__super__.constructor.apply(this, arguments);
    }

    Profiles.resource = "profiles";

    Profiles.object = Profile;

    return Profiles;

  })(Base);

}).call(this);
